apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dorcasmosonik/express_backend:v1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017/yolomy"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: my-app
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
