services:
  frontend:
    image: dorcasmosonik/react_frontend:v1.0.0
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    image: dorcasmosonik/express_backend:v1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

volumes:
  mongo-data:

networks:
  app_network:
    driver: bridge
    name: my_app_network