
- name: Setup MongoDB
  hosts: all
  become: yes
  roles:
    - mongo 

- name: Setup Backend
  hosts: all
  become: yes 
  roles:
    - backend  

- name: Setup Frontend
  hosts: all
  become: yes 
  roles:
    - frontend  
