---
- name: Initial Setup for Docker Project
  hosts: all
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker Python module is installed
      pip:
        name: docker
        state: present

- name: Setup MongoDB
  hosts: all
  roles:
    - mongo 

- name: Setup Backend
  hosts: all
  roles:
    - backend  

- name: Setup Frontend
  hosts: all
  roles:
    - frontend 
