# backend/tasks/main.yml
- name: Build and run backend container
  docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    state: started
    ports:
      - "{{ backend_port }}"
