# frontend/tasks/main.yml
- name: Build and run frontend container
  docker_container:
    name: "{{ frontend_container_name }}"
    image: "{{ frontend_image }}"
    state: started
    ports:
      - "{{ frontend_port }}"
