
- name: Create Docker network for application
  docker_network:
    name: "{{ app_network_name }}"
    state: present

- name: Create docker volume for MongoDB
  docker_volume:
    name: "{{ mongo_volume }}"
    state: present

- name: Run MongoDB container
  docker_container:
    name: "{{ mongo_container_name }}"
    image: "{{ mongo_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ mongo_port }}"
    volumes:
      - "{{ mongo_volume }}:/data/db"
    networks:
      - name: "{{ app_network_name }}"
