
- name: Update apt repository cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - docker.io
    - docker-compose

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true

